#extensions
dot pie: ".py"
dot talon: ".talon"
dot mark down: ".md"
dot shell: ".sh"
dot vim: ".vim"
dot see: ".c"
dot see sharp: ".cs"
dot see plus plus: ".cpp"
dot com: ".com"
dot net: ".net"
dot org: ".org"
dot exe: ".exe"
dot (bin | bend): ".bin"	
dot (jason | jay son): ".json"
dot csv: ".csv"
dot (gammel | why aml): ".yaml"
dot tex: ".tex"
dot jpg: ".jpg"
dot jpeg: ".jpeg"
dot png: ".png"
